from typing import Protocol


class IFileStorage(Protocol):
    def write_bytes(self, key: str, content: bytes) -> str: ...

    def read_bytes(self, key: str) -> bytes: ...

    def exists(self, key: str) -> bool: ...

    def delete(self, key: str) -> None: ...

    def delete_prefix(self, prefix: str) -> None: ...
